### ISSUE TITLE
[Volumes Lecture ]  The default storage Class in minikube

### ISSUE THREAD

**Issue by abdennour** [LevelUpEducation/kubernetes-demo#23]
The DefaultStorageClass admission plugin must be enabled to not encounter issues

### Related Question(s):

- https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/questions/5108602

**Comment by jleetutorial** [comment]
@abdennour, Thanks for opening this issue!

Do we still need 

`minikube addons enable  default-storageclass`

after https://github.com/LevelUpEducation/kubernetes-demo/pull/26 is merged?

**Comment by abdennour** [comment]
No
