### ISSUE TITLE
[Helm Section - Lecture 71] Typo "kube-system" and not "kube.system"

### ISSUE THREAD

**Issue by abdennour** [LevelUpEducation/kubernetes-demo#30]
At the minute 6 and 26 seconds, the instructor ran this command:

```sh
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube.system:tiller

```

This command includes a typo in the value of the last option

# Related Question(s):

- https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/questions/5309032

**Comment by abdennour** [comment]
This is because of a typo :

We need to replace `--serviceaccount=kube.system:tiller` by `--serviceaccount=kube-system:tiller`.

I mean replace `kube.system` by `kube-system`.

I mean replace the dot by the hyphen.

Thus:

```sh
kubectl delete clusterrolebinding tiller
 
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
```

**Comment by jleetutorial** [comment]
@abdennour Thanks for reporting this issue. Just fixed the lecture and re-uploaded to Udemy!
