### ISSUE TITLE
"kubectl run" is deprecated, use "kubectl create" instead

### ISSUE THREAD

**Issue by abdennour** [LevelUpEducation/kubernetes-demo#31]
In the autoscaling lesson the following is run in a second terminal:

```sh
kubectl run -i --tty load-generator --image=busybox /bin/sh
```

After this you get a warning:

```
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.
```

 This issue is a recent issue and it has been already raised by the community 9 days ago:

- issue: https://github.com/kubernetes/examples/issues/277

- migration example from `run` to `create`: https://github.com/kubernetes/examples/pull/280/files

### Related Question (s)

https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/questions/5371892

### Related Lecture

https://www.udemy.com/kubernetes-from-a-devops-kubernetes-guru/learn/v4/t/lecture/9671606?start=0

**Comment by abdennour** [comment]
The original author of this depreciation added a [StackOverflow answer](https://github.com/LevelUpEducation/kubernetes-demo/issues/31). It turns out that the depreciation is not about "kubectl run" in general, but it is about using "kubectl run" with some generators except pods.
As consequence, the lecture should be updated by adding the **generator** explicitly:

Please replace this command:

```sh
kubectl run -i --tty load-generator --image=busybox /bin/sh
```

By this one: 

```sh
kubectl run --generator=run-pod/v1 -i --tty load-generator --image=busybox /bin/sh
```

Note the addition of `--generator=run-pod/v1`.

**Comment by jleetutorial** [comment]
@abdennour  thanks for looking into this. It's now fixed in the video lecture as well as the text lecture.

**Comment by goofy78270** [comment]
so in using the create command, what would be the best way to delete the resources after use is complete, similar to the -rm command in kubectl run

**Comment by gmaghera** [comment]
I'd like to know the same as what @goofy78270 mentioned.  `kubectl run` was a very convenient way to do something in a traceable and auditable manner without much overhead, and with a cleanup included courtesy of the `--rm` flag.  Using `kubectl create job` might be a viable alternate, but it's still a bit heavier than `kubectl run` was/is.

**Comment by gitforwebwork** [comment]
Removing the generators would mean losing a pretty handy tool... it's quite handy to get a base template setup with it, such as:

`kubectl run --generator=deployment/v1beta1 nginx --image=nginx --dry-run --replicas=4 -o yaml > nginx-deployment.yaml`

**Comment by midihenry** [comment]
You can still use `kubectl create`  for the deployments, as follows:
```
$ kubectl create deployment prod --image=busybox --dry-run -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prod
  name: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prod
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
```
However, I think it's limited with it comes to setting some parameters like the number of replicas for example.

**Comment by modevops** [comment]
kubectl create is two limited it needs to have at least --port and --replicas.  They deprecated functionality without replacing functionality.
